nama = input("Nama Lengkap: ")
ttl = input("TTL: ")
alamat = input("Alamat: ")
no_hp = input("Nomer HP: ")
prodi = input("Program Study: ")
hobi = input("hobi: ")
print("Biodata Diri")
print("Nama Lengkap: " + nama)
print("TTL: " + ttl)
print("Alamat: " + alamat)
print("No. Hp: ", no_hp)
print("Program Study: "+ prodi)
print("Hobi: "+ hobi)